@GalleryBackend_HostAddress = http://localhost:8080

GET {{GalleryBackend_HostAddress}}/list
Accept: application/json

###


GET {{GalleryBackend_HostAddress}}/list?path=private
Accept: application/json